### ISSUE TITLE
Several issues observed on Postgres 14.1

### ISSUE THREAD

**Issue by NikolayS** [postgrespro/pg_query_state#40]
Thanks for the great extension.

Tried it on PG 14.1, and had the following issues:

1. TIMING and BUFFERS are not working – tried to set it everywhere, on both sides, globally – doesn't matter, I don't get those numbers in the `pg_query_state` output
2. `leader_pid` is not working as described in README. Maybe there is something that has changed in recent postgres versions (when `leader_pid` appeared in `pg_stat_activity`?), but for parallelized queries, `pg_query_state` always returns a single entry for me -- parallel workers are not displayed. I ended up using this workaround:
   ```sql
    select pid, leader_pid, (select plan from pg_query_state(pid))
    from pg_stat_activity
    where :PID in (pid, leader_pid)  \watch .5
   ```

**Comment by sokolcati** [comment]
It seems the problem may be in the wrong location for setting the guc-variables.
An important point: in order for a pg_query_state() launched in the backend with pid 111 to be able to read statistics on the time/buffers of a query launched in backend 222, the variables must be set in backend 222:
```
backend 222:
SET pg_query_state.enable_timing = on;
-- than run some query

backend 111:
SELECT * FROM pg_query_state(222, true, true, true, true, true);
-- the result contains time statistics
```
Or, to avoid possible misunderstandings, you can set these variables in the configuration file `postgresql.conf` (but it is worth remembering that this may increase overhead, since statistics will be collected for all backends, and not selected ones).
I think I should add this information to the `README.md`.
I hope this answer solves your problem, so I'm closing the issue. If it turns out that the problem was not in the settings, please feel free to create a new issue. Good luck.
